# =========================
#  󰄛  CURSOR  󰄛
# =========================

cursor #9e9e9e
cursor_text_color #111111

cursor_shape block
cursor_shape_unfocused hollow

cursor_beam_thickness 1.5
cursor_underline_thickness 2.0

cursor_blink_interval 0.6 ease-in ease-out
cursor_stop_blinking_after 15.0

cursor_trail 1
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 2
cursor_trail_color none
