# =========================
#  󰄛  KITTY.CONF  󰄛
# =========================

include advance.conf
include fonts.conf
include cursor.conf
include scrollback.conf
include mouse.conf
include performance.conf
include terminal.conf
include layout.conf
include tabbar.conf
include colors.conf
include os.conf
include keyboard.conf
