# =========================
#  󰄛  LAYOUT  󰄛
# =========================

remember_window_size  yes
initial_window_width  640
initial_window_height 400

enabled_layouts tall,stack

draw_minimal_borders no
draw_window_borders_for_single_window yes
window_border_width 2pt
window_margin_width 2.0
window_padding_width 6.0
single_window_margin_width -1
window_padding_width 6.0


placement_strategy center

active_border_color #888888
inactive_border_color #333333
bell_border_color #ff5a00

inactive_text_alpha 1.0

hide_window_decorations yes
