# =========================
#  󰄛  MOUSE  󰄛
# =========================

mouse_hide_wait 3.0

url_color #0087bd
url_style curly
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh

detect_urls yes
underline_hyperlinks hover

copy_on_select a1
map shift+cmd+v paste_from_buffer a1

paste_actions quote-urls-at-prompt,confirm
