# =========================
#  󰄛  SCROLLBACK  󰄛
# =========================

scrollback_lines 2000
scrollbar scrolled

scrollbar_interactive yes
scrollbar_jump_on_click yes

scrollbar_handle_color foreground
scrollbar_track_color foreground

progress_bar top
