---
- name: Install multimedia group
  become: true
  ansible.builtin.dnf:
    name: "@multimedia"
    state: present
    install_weak_deps: false
    exclude:
      - PackageKit-gstreamer-plugin
...
