---
- name: Configure RPM Fusion
  ansible.builtin.import_tasks:
    file: rpmfusion.yaml

- name: Configure Flathub Remote for Flatpak
  ansible.builtin.import_tasks:
    file: flathub.yaml

- name: Install additional codec
  ansible.builtin.import_tasks:
    file: codecs.yaml
...
