---
- name: Configure RPM Fusion
  ansible.builtin.import_tasks:
    file: rpmfusion.yaml

- name: Configure Flathub Remote for Flatpak
  ansible.builtin.import_tasks:
    file: flathub.yaml

- name: Install CLI Tools
  ansible.builtin.import_tasks:
    file: cli_tools.yaml

- name: Configure User
  ansible.builtin.import_tasks:
    file: user.yaml
...
