#!/bin/bash

# for debuggin uncomment this
# set -x

# for adding colors variable
. colors

create_session(){
    session=$1
    window=$2
    windowScript=$3

    session_exists=$(tmux ls 2>/dev/null | grep $session)

    if [[ -n $session_exists ]]
    then
        printf "Session: ${BOLD_MAGENTA} $session${RESET} already exists.\n"
        printf "${CYAN} Attaching ...${RESET}\n"

        tmux a -t $session
    else
        printf "Creating tmux session: ${BOLD_MAGENTA} $session${RESET} ...\n"

        tmux new-session -d -s "$session"
        tmux rename-window -t "$session":1 "$window"
        tmux send-keys -t "$session":"$window" "$windowScript" C-m
        tmux attach-session -t "$session":"$window"
    fi
}

if [[ "$1" == "k" ]]
then
    create_session 'kittycfg-session' '󰄛 KittyConf' \
        'cd ~/.config/kitty/ && clear && nvim kitty.conf'
elif [[ "$1" == "n" ]]
then
    create_session 'nvimcfg-session' ' NeovimConf' \
        'cd ~/.config/nvim/ && clear && nvim init.lua'
elif [[ "$1" == "t" ]]
then
    create_session 'tmuxcfg-session' ' TmuxConf' \
        'cd ~/.config/tmux/ && clear && nvim tmux.conf'
else
    printf "%s\n" \
        "Invalid argument, pass one of the following:" \
        "    k -> For KiTty terminal configuration." \
        "    n -> For Neovim configuration." \
        "    t -> For TMUX configuration."
fi
