---
- name: Install Docker for Fedora
  when: ansible_facts['distribution'] == "Fedora"
  block:
    - name: Add Docker repository
      become: true
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/fedora/docker-ce.repo"
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'

    - name: Install Docker Packages
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Enable and Start Docker Unit
      become: true
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
        state: started
...
